### ISSUE TITLE
Programs Folder

### ISSUE THREAD

**Issue by robert478** [JoelShine/JARVIS-AI-ASSISTANT#1]
How does one get to use the sub folder programs in the Standard folder.
Can't open any thru jarvis.py

**Comment by JoelShine** [comment]
Actually saying, the programs folder in the standard folder is not used for opening directly through <b>jarvis.py</b> but it is accessed by AIML. You can see this in the <b>'standard/launch.aiml' </b> file. In that file, you can see the command used to open that files. Hope it helps !

**Comment by robert478** [comment]
I must be missing something , I say open google and i get a bash error and it freezes up. Maybe its a linux thing.

**Comment by JoelShine** [comment]
Are using Linux ? This is tested in Windows only. So if you are in linux, it may not work.

**Comment by JoelShine** [comment]
Make sure you also have vosk with you.
